trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.1.0

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37, py38]  # , latest_pip]
    os: linux
